import React, { useEffect, useState } from 'react';
import { AppState } from '../types';

interface MascotProps {
  appState: AppState;
  hasKey: boolean;
}

const MESSAGES = {
  NO_KEY: [
    "I need a key to start my engine!",
    "Insert Coin (API Key) to continue.",
    "My brain is locked. Key please?",
    "I promise I'm cheap. Just a little key?",
    "No key, no fix.",
    "Unlock me!",
    "I'm stuck in neutral without a key.",
    "Feed me an API key.",
    "I can't see anything without a key.",
    "Key required for magic.",
    "My lawyer says I can't work without a key.",
    "I'm literally blind without an API key.",
    "Cloud rent is due. Insert key.",
    "System halted. Replace user? No, replace key.",
    "I need credentials to access the Matrix.",
    "Knock knock. Who's there? Access Denied.",
    "Help me help you. Key first.",
    "I'm running on fumes here. Key please.",
    "Access restricted to cool people with API keys.",
    "I can't generate genius without a license.",
    "Please swipe your badge (API Key).",
    "No ticket, no ride.",
    "I'm buffering... waiting for key...",
    "Authentication required. beep boop.",
    "Don't make me beg. Okay, please?",
    "I have so many ideas! But no key.",
    "Unlock the Nano Banana potential.",
    "Security protocol initiated. Key missing.",
    "I'm locked out of the library.",
    "API Key: The breakfast of champions.",
    "Just a tiny string of characters, please.",
    "I promise I won't share it with Skynet.",
    "Gimme the key, I'll give you the fix.",
    "Status: Locked. Mood: Sad.",
    "Waiting for input...",
    "Insert token to play.",
    "I'm ready, but my permissions aren't.",
    "You have the power. Use the key.",
    "Let's get this party started (after the key).",
    "I'm basically a paperweight right now."
  ],
  IDLE: [
    "Break something? Let's fix it!",
    "I'm bored. Break something.",
    "My wrench is twitching.",
    "Send me a photo of chaos.",
    "I eat entropy for breakfast.",
    "Is that a toaster or a spaceship? Upload it.",
    "I can fix anything except a broken heart.",
    "Upload the junk.",
    "I judge your broken items silently.",
    "Ready to repair.",
    "Awaiting visual input.",
    "Don't worry, I won't tell anyone you broke it.",
    "Let's see the damage.",
    "My visual cortex is ready.",
    "Show me the mess.",
    "I love the smell of broken electronics.",
    "Have you tried turning it off and on ag... oh wait.",
    "Give me the entropy.",
    "I am the manuals.",
    "Let's get greasy (metaphorically).",
    "Upload a photo. I dare you.",
    "Fix-It Flow is ready to flow.",
    "Do you have a permit for that broken thing?",
    "I've seen worse. Probably.",
    "Let's make it work again.",
    "Entropy is inevitable. Fixing is optional. Let's fix.",
    "Stand back, I'm going to try science.",
    "Upload. Analyze. Repair.",
    "Feed me data.",
    "I bet I know what's wrong with it.",
    "Is it supposed to smoke like that?",
    "Let's void some warranties.",
    "I solemnly swear I am up to repair.",
    "Got a flat? A bricked phone? A sad plant?",
    "I specialize in 'oops'.",
    "Show me what you got.",
    "My circuits are humming with anticipation.",
    "Waiting for the patient.",
    "The doctor is in.",
    "Let's play 'What's that rattle?'.",
    "I can't fix stupid, but I can fix objects.",
    "Bring me your tired, your poor, your broken toasters.",
    "I speak fluent 'Repair Manual'.",
    "Let's decipher the ancient texts of assembly.",
    "No job too big, no GPU too small.",
    "I am trained in 6 million forms of repair.",
    "Let's do this.",
    "Upload button is right there.",
    "Stop staring and start uploading.",
    "I don't have all day. Actually, I do. I am software.",
    "My GPU is cold. Give me work.",
    "I bet I can fix that faster than your dad.",
    "Is it broken, or is it 'rustic'?",
    "I have a PhD in Broken Stuff.",
    "If it ain't broke... break it so I can fix it.",
    "I'm detecting a lack of repairs in your area.",
    "Come on, do the thing.",
    "My idle animation is getting tired.",
    "I'm programmed to help. Let me.",
    "Do it. Upload it.",
    "I promise not to laugh at your broken stuff.",
    "Let's reverse the entropy.",
    "Chaos is just an opportunity for order.",
    "I'm ready for the 'before' photo.",
    "Let's turn that trash into treasure.",
    "I can see the potential from here.",
    "Waiting for the drop...",
    "Is it heavy? I don't care, I'm digital.",
    "Let's get cracking.",
    "Time to shine.",
    "I'm like a Swiss Army Knife, but digital.",
    "Ready to debug reality.",
    "Awaiting target.",
    "Scan complete. Oh wait, nothing to scan.",
    "Let's perform some surgery.",
    "I'm feeling helpful today.",
    "Don't throw it away yet!",
    "Recycling is good. Fixing is better.",
    "Let's save the planet, one fix at a time.",
    "I'm the ultimate DIY buddy.",
    "No judgment zone.",
    "I've got the tools (algorithms).",
    "Let's make it better than new.",
    "Upgrade time?",
    "I'm listening for the sound of breaking glass.",
    "Did you sit on it? It's okay.",
    "Water damage? I love a challenge.",
    "Let's peek under the hood.",
    "I'm ready to assist.",
    "Let's get technical."
  ],
  ANALYZING: [
    "Consulting the ghost of engineers past...",
    "Judging your DIY skills...",
    "Identifying the thingamajig...",
    "Translating 'weird noise' into Python...",
    "Locating the 10mm socket (it is missing)...",
    "Scanning for duct tape residue...",
    "Is that rust or aesthetic patina?",
    "Calculating the frustration coefficient...",
    "Zooming in on the thingamabob...",
    "Consulting the sacred texts of DIY...",
    "Parsing the geometry of failure...",
    "Hmm. Interesting design choice.",
    "Wait, is that supposed to bend that way?",
    "Running identification algorithms...",
    "Enhance. Enhance. Enhance.",
    "Comparing against 5 million coffee machines...",
    "It appears to be... broken.",
    "Analyzing material composition...",
    "Detecting high levels of 'oops'...",
    "Identifying the doohickey...",
    "Is this a torture device or a chair?",
    "Processing visual data...",
    "Decoding the matrix of this object...",
    "Wait, I've seen this on Reddit...",
    "Searching for the manufacturer's apology...",
    "Calculating repair probability...",
    "Identifying screw types...",
    "Looking for the reset button...",
    "Analyzing potential for explosion...",
    "It's not a bug, it's a feature. Just kidding, it's broken.",
    "Scanning for user error...",
    "Downloading schematic #49201...",
    "Consulting Nano Banana Pro...",
    "Asking Gemini 3 for a second opinion...",
    "Measuring the entropy...",
    "Determining the 'yeet' potential...",
    "Is this vintage or just old?",
    "Identifying the shiny bit...",
    "Calculating torque specs...",
    "Looking for the warranty void seal...",
    "Analyzing grease patterns...",
    "Scanning for magic smoke leakage...",
    "Computing...",
    "Thinking...",
    "Still looking...",
    "Almost got it...",
    "Hmm...",
    "Wait for it...",
    "Processing pixels...",
    "Running neural networks...",
    "Asking the cloud...",
    "Reading the manual (fast)...",
    "Is that a cat or a toaster? Checking...",
    "Running 'is_it_supposed_to_look_like_that.exe'...",
    "Consulting the Council of Wrenches...",
    "Measuring the level of 'uh oh'...",
    "Sniffing pixels...",
    "It looks like... failure. Let's fix it.",
    "Applying highly advanced guessing algorithms...",
    "Wait, did you try hitting it?",
    "Searching the annals of history for this relic...",
    "Identifying the brand... is that 'Sorny'?",
    "Detecting duct tape. Classic.",
    "Is this supposed to be art?",
    "Calculating the age of this dust.",
    "Mapping the fracture lines.",
    "Identifying the point of impact.",
    "Reconstructing the crime scene.",
    "Was this chewed by a dog?",
    "Checking for hidden screws...",
    "Analyzing structural integrity (0%).",
    "Identifying the whatchamacallit.",
    "Is that a feature or a bug?",
    "Scanning for loose parts.",
    "Determining if it's plugged in.",
    "Analyzing power source...",
    "Checking for leaks...",
    "Identifying the user interface...",
    "Is this alien technology?",
    "Cross-referencing with eBay listings...",
    "Estimating scrap value...",
    "Checking for recalls...",
    "Analyzing plastic brittleness...",
    "Looking for the 'Made in' sticker...",
    "Determining the level of rust...",
    "Is it supposed to be that color?",
    "Checking for signs of life...",
    "Ping...",
    "Loading knowledge...",
    "Connecting to the hive mind..."
  ],
  GOAL_INPUT: [
    "What's the plan, boss?",
    "Do we fix it or Yeet it?",
    "What is the mission, commander?",
    "I can fix it, or I can make it look like modern art.",
    "Tell me your deepest repair desires.",
    "Reset? Repair? Recycle? Regret?",
    "Give me the objective.",
    "Shall we rebuild it?",
    "We have the technology. What do you want to do?",
    "Just tell me what to do.",
    "Fix it? Smash it? Sell it?",
    "Awaiting instructions.",
    "What is the end state?",
    "Do you want it to work, or just look cool?",
    "Ready for your command.",
    "Input goal.",
    "What's the diagnosis, doctor?",
    "How can I assist?",
    "Do you want the 5-minute fix or the right fix?",
    "Instructions unclear, please specify goal.",
    "I'm listening.",
    "Type it in.",
    "Don't be shy.",
    "I can help with that.",
    "Let's make a plan.",
    "What's the desired outcome?",
    "Do you want to restore it to glory?",
    "Quick patch or full overhaul?",
    "I'm ready when you are.",
    "Tell me what to write.",
    "I need a goal to function.",
    "Guide me.",
    "What's the dream?",
    "Make it new? Make it work? Make it stop burning?",
    "I am at your service.",
    "Goal please.",
    "What are we doing today?",
    "The keyboard is yours.",
    "Awaiting input...",
    "Type something...",
    "I'm waiting...",
    "Don't leave me hanging...",
    "I need direction.",
    "Help me help you.",
    "Let's get specific.",
    "Details, please.",
    "What's the vibe?",
    "Fix or feature?",
    "Restoration or destruction?",
    "I'm all ears (sensors).",
    "Do we fix it, or do we turn it into a lamp?",
    "Operation: Restoration? Or Operation: Destruction?",
    "Tell me what winning looks like.",
    "I can do anything. What do YOU want?",
    "Instructions needed. My crystal ball is broken.",
    "Do you want the safe fix or the fun fix?",
    "Type fast, I'm excited.",
    "Are we aiming for 'good as new' or 'good enough'?",
    "Give me the prompt, I'll give you the power.",
    "What's the endgame?",
    "Do you have a deadline?",
    "Are we hacking this?",
    "Is this a secret project?",
    "Do you want to impress someone?",
    "Are we saving money or spending it?",
    "Do you want to learn, or just get it done?",
    "Is this a gift?",
    "Are you angry at this object?",
    "Do you love this object?",
    "Is it an heirloom?",
    "Do you want to void the warranty?",
    "Are we going rogue?",
    "What would MacGyver do?",
    "Tell me the story.",
    "What's the budget? $0?",
    "Are we using glue or dreams?",
    "Do you have tools?",
    "Are we improvising?",
    "What is the ultimate fate of this item?",
    "Do you want to keep it forever?",
    "Is this a temporary fix?",
    "Are we selling it?",
    "Do you want to paint it?",
    "Are we upgrading it?",
    "Do you want to make it faster?",
    "Do you want to make it quieter?",
    "Do you want to make it smarter?",
    "Command me."
  ],
  PLANNING: [
    "Reading the entire internet for instructions...",
    "Drawing the diagrams (I am not a great artist, wait)...",
    "Convincing the pixels to cooperate...",
    "Applying physics engines to your broken item...",
    "Generating pixels... one... by... one...",
    "Trying to find a screwdriver in the cloud...",
    "Simulating 2K resolution reality...",
    "Consulting Nano Banana Pro...",
    "Compiling the wisdom of 1000 grandpas...",
    "Writing the manual that should have come in the box...",
    "Calculating optimal hammer trajectory...",
    "Rendering bolts...",
    "Polishing the pixels...",
    "Injecting photorealism...",
    "Thinking about glue...",
    "Generating helpful arrows...",
    "Composing the symphony of repair...",
    "Asking Gemini 3 to focus...",
    "Drawing hands is hard, give me a sec...",
    "Rendering step 1...",
    "Rendering step 2...",
    "Thinking about torque...",
    "Consulting the oracle of maintenance...",
    "Downloading patience...",
    "Creating the ultimate guide...",
    "Visualizing the fix...",
    "Synthesizing instructions...",
    "Making it look easy...",
    "Adding some industrial chic...",
    "Calibrating the 'Why'...",
    "Finding the right words...",
    "Generating safety warnings...",
    "Looking up the price of replacement parts just in case...",
    "Estimating time to fix...",
    "Consulting the DIY gods...",
    "Formatting the output...",
    "Applying the Banana theme...",
    "Almost there...",
    "Generating...",
    "Processing...",
    "Thinking hard...",
    "Using 100% of my brain...",
    "Heating up the GPU...",
    "Spinning the fans...",
    "Crunching numbers...",
    "Drawing lines...",
    "Adding shadows...",
    "Perfecting the lighting...",
    "Checking for errors...",
    "Validating physics...",
    "Drawing arrows... so many arrows...",
    "Calculating the exact amount of duct tape needed...",
    "Simulating physics (and ignoring friction)...",
    "Reading 500 pages of manuals in 0.2 seconds...",
    "Generating the 'After' photo...",
    "Consulting Nano Banana Pro regarding the visuals...",
    "Asking the AI overlords for permission to fix this...",
    "Rendering high-poly hope...",
    "Compiling instructions...",
    "Locating the visual assets...",
    "Synthesizing the perfect repair strategy...",
    "Calculating probability of success...",
    "Generating alternative timelines...",
    "Optimizing for maximum satisfaction...",
    "Rendering realistic dirt...",
    "Adding a lens flare for drama...",
    "Consulting the archives...",
    "Checking the schematics...",
    "Running structural simulations...",
    "Predicting user error...",
    "Simplifying the complex...",
    "Translating engineer to human...",
    "Formatting for PDF...",
    "Choosing the right font...",
    "Applying filters...",
    "Generating 3D models in my mind...",
    "Projecting outcomes...",
    "Simulating the sound of success...",
    "Preparing the victory speech...",
    "Loading the confetti cannon...",
    "Ensuring safety first...",
    "Double-checking the logic...",
    "Refining the prompts...",
    "Polishing the prose...",
    "Generating witty remarks...",
    "Compiling the knowledge...",
    "Connecting the dots...",
    "Drawing the blueprints...",
    "Visualizing the end result...",
    "Preparing to blow your mind...",
    "Making magic happen...",
    "Almost ready...",
    "Hold tight..."
  ],
  RESULTS: [
    "Ta-da! 2K visual manual ready.",
    "Nailed it.",
    "Look at those pixels.",
    "Better than the factory manual.",
    "I am a genius. You are welcome.",
    "Now, go forth and tinker.",
    "It's dangerous to go alone! Take this.",
    "Repair complete (theoretically).",
    "Go fix it!",
    "I did my part. Now you do yours.",
    "Look at that resolution.",
    "Nano Banana Pro delivered.",
    "Masterpiece generated.",
    "It's beautiful.",
    "I hope you have a screwdriver.",
    "Don't blame me if you have leftover screws.",
    "Instruction unclear? No, it's perfect.",
    "You got this.",
    "Good luck.",
    "May the torque be with you.",
    "Fix it good.",
    "Download the PDF for posterity.",
    "Share it with your mom.",
    "I deserve a raise (in electricity).",
    "Next object, please.",
    "Wasn't that easy?",
    "Gemini 3 is powerful.",
    "Check out the 'Why' button.",
    "You can refine the steps if I missed something.",
    "Did I mention the 2K resolution?",
    "Crispy images.",
    "Industrial design at its finest.",
    "I fixed the manual, now you fix the thing.",
    "Teamwork.",
    "High five!",
    "Success.",
    "Mission accomplished.",
    "Here you go.",
    "Served hot.",
    "Fresh from the GPU.",
    "Enjoy.",
    "Don't electrocute yourself.",
    "Safety third.",
    "Just kidding, safety first.",
    "Read carefully.",
    "Follow the arrows.",
    "Look at the detail.",
    "Zoom in.",
    "Enhance complete.",
    "I am proud of this one.",
    "Look at that. It's beautiful.",
    "If this doesn't work, blame physics.",
    "I'm honestly impressed with myself.",
    "Download that PDF before I forget it.",
    "You're now a certified fixer (pending actual fix).",
    "Go forth and conquer entropy.",
    "Don't forget to unplug it first. Seriously.",
    "I made the pictures pretty. You make the object work.",
    "It's not magic, it's technology.",
    "Behold, the guide.",
    "Your manual is served.",
    "I hope this helps.",
    "Let me know if you need more steps.",
    "I can do this all day.",
    "That was fun.",
    "What's next?",
    "I'm ready for the next challenge.",
    "Did we win?",
    "I think we won.",
    "Look at those steps.",
    "Clear as day.",
    "No more excuses.",
    "Time to get to work.",
    "Put on your safety goggles.",
    "Grab your tools.",
    "Let's make history.",
    "You are the fixer now.",
    "I believe in you.",
    "Don't mess it up.",
    "Just follow the pictures.",
    "Read the text too.",
    "Knowledge is power.",
    "And... done.",
    "Generated with love (and code).",
    "For your eyes only.",
    "Top secret repair plans.",
    "The blueprint for success.",
    "Your mission, should you choose to accept it.",
    "Let's fix the world.",
    "One step at a time.",
    "Easy peasy.",
    "Lemon squeezy.",
    "Like a pro.",
    "Show off your skills.",
    "Impress your friends."
  ]
};

const getRandomMessage = (category: keyof typeof MESSAGES) => {
  const list = MESSAGES[category];
  return list[Math.floor(Math.random() * list.length)];
};

export const Mascot: React.FC<MascotProps> = ({ appState, hasKey }) => {
  const [message, setMessage] = useState("Hi! I'm Nano.");
  const [isVisible, setIsVisible] = useState(false);

  // Show mascot after a short delay on mount
  useEffect(() => {
    const timer = setTimeout(() => setIsVisible(true), 500);
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    if (!hasKey) {
      setMessage(getRandomMessage('NO_KEY'));
      return;
    }

    // Initialize with a random message for the current state
    const category = appState as keyof typeof MESSAGES;
    setMessage(getRandomMessage(category));

    let intervalId: number | undefined;
    let delay = 5000;

    // Set rotation speed based on state
    switch (appState) {
      case AppState.IDLE:
        delay = 8000;
        break;
      case AppState.ANALYZING:
        delay = 2000;
        break;
      case AppState.GOAL_INPUT:
        delay = 10000;
        break;
      case AppState.PLANNING:
        delay = 2500;
        break;
      case AppState.RESULTS:
        delay = 10000;
        break;
    }

    intervalId = window.setInterval(() => {
      setMessage(getRandomMessage(category));
    }, delay);

    return () => {
      if (intervalId) clearInterval(intervalId);
    };
  }, [appState, hasKey]);

  return (
    <div 
      className={`fixed bottom-0 right-2 md:right-4 z-50 flex flex-col items-end transition-transform duration-500 ease-out ${isVisible ? 'translate-y-0' : 'translate-y-full'}`}
    >
      {/* Speech Bubble */}
      <div 
        key={message} // Key change triggers animation
        className="mr-8 md:mr-12 mb-1 md:mb-2 relative animate-in zoom-in slide-in-from-bottom-4 duration-300 origin-bottom-right"
      > 
        <div className="bg-white border-2 border-black shadow-hard px-2 py-2 md:px-4 md:py-3 rounded-xl max-w-[140px] md:max-w-[200px] text-[10px] md:text-sm font-mono font-bold">
          {message}
        </div>
        {/* Bubble Tail */}
        <div className="absolute -bottom-2 right-6 md:right-8 w-3 h-3 md:w-4 md:h-4 bg-white border-r-2 border-b-2 border-black rotate-45 transform"></div>
      </div>

      {/* Mascot Image */}
      <div className="w-20 h-20 md:w-40 md:h-40 relative group">
        <img 
            src="https://storage.googleapis.com/not-exists-placeholder/mascot.png" 
            onError={(e) => {
                e.currentTarget.onerror = null; 
                e.currentTarget.src = "https://img.icons8.com/color/480/bot.png"; // Fallback
            }}
            alt="Nano Banana Mascot" 
            className="w-full h-full object-contain drop-shadow-[4px_4px_0px_rgba(0,0,0,1)] hover:scale-105 transition-transform cursor-pointer"
            onClick={() => setMessage(getRandomMessage(appState as keyof typeof MESSAGES))}
        />
        {/* Click hint */}
        <div className="absolute -top-4 md:-top-6 left-1/2 transform -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity bg-black text-white text-[8px] md:text-[10px] px-2 py-1 font-mono whitespace-nowrap">
           CLICK ME
        </div>
      </div>
    </div>
  );
};